# PostgreSQL Client Authentication Configuration
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Connexions locales (healthcheck)
local   all             all                                     trust

# SSL obligatoire depuis le réseau db (Mastodon → PostgreSQL)
hostssl mastodon_production mastodon        172.33.3.0/24           scram-sha-256

# Refuser tout le reste
host    all             all             all                     reject
